<Project>
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
	<TargetJellyfinRef>v10.11.0-rc5</TargetJellyfinRef>
	<MSBuildProjectExtensionsPath>build\$(TargetJellyfinRef)</MSBuildProjectExtensionsPath>
	<BaseIntermediateOutputPath>$(MSBuildProjectExtensionsPath)\obj</BaseIntermediateOutputPath>
	<BaseOutputPath>$(MSBuildProjectExtensionsPath)\bin</BaseOutputPath>
  </PropertyGroup>
  
  <Import Project="JellyfinLoaderStub-common.csproj" />
</Project>
