name: 'Create NuGet release'
on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Release type'
        required: true
        type: choice
        options:
        - major
        - minor
        - patch
jobs:
  create_nuget_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: '24.x'
      - run: node .github/workflows/node/increase-version.js JellyfinLoaderStub/JellyfinLoaderStub-common.csproj ${{inputs.release_type}}
